apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: sample-automated-analysis
    lifetimeMinutes: 05
    gitops: true
    passScore: 60
    serviceList:
    - metricTemplateName: "metrictemplate"
      metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "argo-sampleapp,.*{{env.STABLE_POD_HASH}}.*,opsmx-demo"
      canaryMetricScope: "argo-sampleapp,.*{{env.LATEST_POD_HASH}}.*,opsmx-demo"
      logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateName: "logtemplate"
